#! /bin/bash
#SBATCH -A see200002p	# specify the project or allocation number
#SBATCH -p RM-shared	# RM-shared partition
#SBATCH -J myjob	# Job name
#SBATCH --mail-user=bdelled@udel.edu
#SBATCH --mail-type=ALL

#SBATCH -N 1		# Number of nodes, not cores (16 cores/node)
#SBATCH -n 64		# Number of cores requested in total

#SBATCH -t 00:15:00

./brute_parallel
